# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[docker_context]
format = '[ğŸ‹ $context](blue bold)'
disabled = false

[directory]
home_symbol = "ó°‹œ ~"
format = "[$path]($style)[$read_only]($read_only_style) "
disabled = false
truncation_length = 20
truncation_symbol = 'â€¦/'

[git_branch]
format = "[$symbol$branch]($style) "
truncation_symbol = "â€¦/"
style = "bold green"
disabled = false

# Shows current git status
[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
disabled = false


[kubernetes]
symbol = 'ó±ƒ¾'
format = '[$symbol $context \($namespace\) ](bold purple) '
disabled = false
contexts = [
  { context_pattern = "dev.local.cluster.k8s", style = "green", symbol = "ğŸ’” " },
]
